# -*- coding: utf-8 -*-
"""cairo.pynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cCAPSQI9px43xoiWyDO6mkhqklhA-ZuK
"""

import pandas as pd
import numpy as np
from shapely.geometry import Point
from shapely.geometry.polygon import Polygon


data =pd.read_csv('/content/Cairo neighborhoods.csv')
res_data =pd.read_csv('/content/res_data.csv')
def my_function(lat,long):
 for j in range(0, len(data)):
#---------------found array of x values for one neighborhood-----------------------#
  xranges  = data["x values"][j].split(',')
  x = np.array(xranges)
  x = x.astype(np.float)
#---------------found array of y values for one neighborhood-----------------------#
  yranges  = data["y values"][j].split(',')
  y = np.array(yranges)
  y = y.astype(np.float)
  f=()
  point = Point(lat,long)
  
  for i in range(0, len(x)):
     l= (x[i],y[i])
     f=(l,)+f
  polygon = Polygon(f)
  if(polygon.contains(point)):
     return data["neighborhood"][j]

 return "not found"


#---------------------check on data to identify neighborhoods#--------------------------------

neighborhoods = []
for j in range(0, len(res_data)):
  lat = res_data["latitude"][j]
  long = res_data["longitude"][j]
  neighborhoods.append(my_function(lat,long))

res_data.insert(6,"neighborhoods",neighborhoods,True)
res_data.to_csv (r'Cairo_shopping_data.csv', index = False, header=True)  


#my_function(30.035258, 31.212613)

